name: Manual Python Setup

on:
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Python version'
        type: choice
        required: true
        options:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'

jobs:
  setup-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python_version }}

      - name: Verify Python installation
        run: |
          python --version
          which python
